version: '3'

services:
  eprintsdb:
    build:
      context: .
      dockerfile: eprintsdb.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: tameness-peddling-humped
      MYSQL_DATABASE: eprints
      MYSQL_USER: eprints_user
      MYSQL_PASSWORD: wilder-landscape-chrome
    ports:
      - "3306:3306"
    networks:
      - eprints_network
    volumes:
      - eprintsdb_data:/var/lib/mysql

  eprintshttpd:
    build:
      context: .
      dockerfile: eprintshttpd.dockerfile
    depends_on:
      - eprintsdb
    ports:
      - "80:80"
    networks:
      - eprints_network
    volumes:
      - eprintshttpd_data:/usr/share/eprints3
      - eprintshttpd_etc:/etc/eprints3
      - eprintshttpd_var:/var/lib/eprints3
    dns:
      - 8.8.8.8

networks:
  eprints_network:
    driver: bridge

volumes:
  eprintsdb_data:
  eprintshttpd_data:
  eprintshttpd_etc:
  eprintshttpd_var:
